### ISSUE TITLE
NameError: name 'run' is not defined

### ISSUE THREAD

**Issue by EJD222** [mazqoty/Yolo-v5-Streamlit-App-Pretrained-Model#1]
Object Detection is not running, I get the same error below every time I click the "Detect" button.

![image](https://user-images.githubusercontent.com/91679071/209265597-0356669b-1660-42c2-add2-e1eb31247c0b.png)

**Comment by mm-mazhar** [comment]
I think you are running it on windows, I only tested on linux..i have done
some changes for windows run it again from scratch it should fix
the problem, it didn't install yolov5,
let me know if the error is gone.

**Comment by mm-mazhar** [comment]
it should work now

**Comment by EJD222** [comment]
Yeah thanks. But this happens, when I click "Detect" it does not output the Object Detection but it outputs the balloons.

![image](https://user-images.githubusercontent.com/91679071/209314039-a09364ef-fd25-4cbb-b398-0630bdcc9835.png)
