### ISSUE TITLE
But this happens, when I click "Detect" it does not output the Object Detection but it outputs the balloons.

### ISSUE THREAD

**Issue by EJD222** [mazqoty/Yolo-v5-Streamlit-App-Pretrained-Model#2]
Yeah thanks. But this happens, when I click Detect it does not output the Object Detection but it outputs the balloons.

![image](https://user-images.githubusercontent.com/91679071/209314039-a09364ef-fd25-4cbb-b398-0630bdcc9835.png)

_Originally posted by @EJD222 in https://github.com/mazqoty/Yolo-v5-Streamlit-App-Pretrained-Model/issues/1#issuecomment-1363798917_

**Comment by mm-mazhar** [comment]
it didn't detect.
I tried on my PC (windows). There may be some installation issues
![detected_Bus](https://user-images.githubusercontent.com/34889453/209318316-f6cde425-3fbf-4fe8-82b0-d5cdb46bcdf6.jpg)

**Comment by EJD222** [comment]
I'll try again.

**Comment by mm-mazhar** [comment]
all the relevent installations are in 'yolov5setup.py' file 
try to do it from scratch
remove your existing installation/environment e.g. `conda env remove -n ENV_NAME`
then follow the README.md file in this repository again
if you encounter any error related to modules e.g if it says no module named Numpy then `pip uninstall numpy` and then reinstall it `pip install numpy`

**Comment by EJD222** [comment]
I'll try. Thanks a lot.

**Comment by mm-mazhar** [comment]
create environment from conda instead of venv
usually conda environments works good especially with tensorflow and pytorch

**Comment by EJD222** [comment]
It's working now. Thank you!

**Comment by mm-mazhar** [comment]
welcome
